<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_landscape-image</name>
   <tag></tag>
   <elementGuidId>fda55251-3833-4a49-ad1b-3ac3aafdf188</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='DaoU8F0BjAAFRW9Cc17iHQ']/div[2]/div/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.a-link-normal.image-redirect.aok-block.image-window > div.a-section.a-spacing-none.fluid-image-container > img.landscape-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9d6c493f-04ee-4a93-ad7a-ae08821a019e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Women's fashion</value>
      <webElementGuid>f9095ace-d2d5-4b12-a0e1-65d64fe49521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images-na.ssl-images-amazon.com/images/G/01/AMAZON_FASHION/2020/journeys/NTE3Zjc1NTEt/NTE3Zjc1NTEt-ZWVhMjc2YjAt-w186._SY116_CB410473316_.jpg</value>
      <webElementGuid>7423bfd1-3083-49c3-8f96-a12f99bcba3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>landscape-image</value>
      <webElementGuid>efd25ab3-5736-4a60-b21d-609b08a15f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-hires</name>
      <type>Main</type>
      <value>https://images-na.ssl-images-amazon.com/images/G/01/AMAZON_FASHION/2020/journeys/NTE3Zjc1NTEt/NTE3Zjc1NTEt-ZWVhMjc2YjAt-w372._SY232_CB410434712_.jpg</value>
      <webElementGuid>62cfdf51-0dac-4240-a5cb-4952e458b709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DaoU8F0BjAAFRW9Cc17iHQ&quot;)/div[@class=&quot;a-cardui-body&quot;]/div[@class=&quot;a-section a-spacing-small grid-row-1&quot;]/div[@class=&quot;a-section a-spacing-none quadrant-container quadrant-container-0&quot;]/a[@class=&quot;a-link-normal image-redirect aok-block image-window&quot;]/div[@class=&quot;a-section a-spacing-none fluid-image-container&quot;]/img[@class=&quot;landscape-image&quot;]</value>
      <webElementGuid>3280ccc8-e204-4b57-a9a2-0edf84f66800</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DaoU8F0BjAAFRW9Cc17iHQ']/div[2]/div/div/a/div/img</value>
      <webElementGuid>1d1c8222-65ce-4070-84f9-419a7f314280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt=&quot;Women's fashion&quot;]</value>
      <webElementGuid>542cf8c5-dc09-4140-9565-7c58f0bfb358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/div/img</value>
      <webElementGuid>53ceb0ab-6ae5-4825-ad55-7a161c76d1ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = concat(&quot;Women&quot; , &quot;'&quot; , &quot;s fashion&quot;) and @src = 'https://images-na.ssl-images-amazon.com/images/G/01/AMAZON_FASHION/2020/journeys/NTE3Zjc1NTEt/NTE3Zjc1NTEt-ZWVhMjc2YjAt-w186._SY116_CB410473316_.jpg']</value>
      <webElementGuid>e4933b14-1f9d-4de3-bce8-d9eeb94ef7bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
