<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cvf_captcha_captcha_action</name>
   <tag></tag>
   <elementGuidId>fcdcf66d-0e05-42e4-9876-a22b489a4631</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cvf_captcha_captcha_action&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cvf_captcha_captcha_action']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10ec59e7-fbc5-4480-9235-ea4df7216c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cvf_captcha_captcha_action</value>
      <webElementGuid>479ac874-ab0f-4770-a9e6-7308464cb913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input notranslate</value>
      <webElementGuid>daf1d50d-1a1e-40d2-85cc-44d40ca64707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>95c962f0-72a7-4a03-a24f-40bc2333a595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>verifyCaptcha</value>
      <webElementGuid>b986cae3-89b5-4d0a-801c-06666d9e1983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>a-autoid-0-announce</value>
      <webElementGuid>b460e412-4cd0-43ef-90cf-096c9e55b3a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-autoid-0&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input notranslate&quot;]</value>
      <webElementGuid>a7bcddbe-116a-466a-b90c-e2f86e7e4f55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cvf_captcha_captcha_action']</value>
      <webElementGuid>6da35183-2a8d-4f96-acca-51d6344db72e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-0']/span/input</value>
      <webElementGuid>54a26bf6-a28d-450b-993b-3d3a77635400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>6cbf72cc-3949-4600-a5bc-17b3b00495c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cvf_captcha_captcha_action' and @type = 'submit']</value>
      <webElementGuid>5daa9baa-bdc3-45e4-8b2f-9addc3c35f70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
