<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Hello, sign in</name>
   <tag></tag>
   <elementGuidId>3ae35212-ecae-42d0-885e-4f7c9aca7329</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-link-accountList-nav-line-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='nav-link-accountList-nav-line-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>91c1c654-b9d0-4ddd-ae86-450cdeb88d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-link-accountList-nav-line-1</value>
      <webElementGuid>c7c8dc31-8448-4367-9aa9-a1d55e30b190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-line-1 nav-progressive-content</value>
      <webElementGuid>d61085a8-9b06-4b49-bd53-7f5031e054a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hello, sign in</value>
      <webElementGuid>ff795d7c-3d1f-415e-af9b-2e9da52d888f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-link-accountList-nav-line-1&quot;)</value>
      <webElementGuid>f2422ad3-4d37-469d-aef7-b81e9af9f51a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='nav-link-accountList-nav-line-1']</value>
      <webElementGuid>cba19aaf-7238-41ab-ac33-e9c42875ee57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='nav-link-accountList']/div/span</value>
      <webElementGuid>8161b3b3-8b59-4684-9cac-3b3185231b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/span</value>
      <webElementGuid>290870b7-533f-4266-9e51-68e50bc1da83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'nav-link-accountList-nav-line-1' and (text() = 'Hello, sign in' or . = 'Hello, sign in')]</value>
      <webElementGuid>e0a69a8b-8748-4b48-946a-21d15e34de4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
