<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_a-button-input</name>
   <tag></tag>
   <elementGuidId>1cb4b904-62a5-43be-b39f-d28d3bc34392</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='submit'])[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GLUXZipUpdate > span.a-button-inner.a-declarative > input.a-button-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>786336f1-00ec-42d5-b406-53d29c6d3229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>ab89e4d2-56af-4dec-8227-38868dda4fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>301a6162-8239-4f81-9025-d607ae1b161b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>GLUXZipUpdate-announce</value>
      <webElementGuid>bec6f2ec-89e7-448c-b7e0-583dd4f4d6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GLUXZipUpdate&quot;)/span[@class=&quot;a-button-inner a-declarative&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>fdaf69f1-ab73-4465-be2a-bce9ac20cf70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='submit'])[8]</value>
      <webElementGuid>c01936e5-7fd0-4875-a149-58a93fe3dfc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='GLUXZipUpdate']/span/input</value>
      <webElementGuid>cdc88e50-d993-4f93-9565-72a44cf38421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/input</value>
      <webElementGuid>77b15a1a-13c7-403e-a84a-e0c78d5321b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>0275e211-5193-4c29-88cc-2e23016d243c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
