<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputGLUXZipUpdateInput</name>
   <tag></tag>
   <elementGuidId>f03cee22-9e4d-4777-8c61-6279217941a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GLUXZipUpdateInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GLUXZipUpdateInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e81b5213-eacb-4216-8146-d36fd233b697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GLUX_Full_Width a-declarative</value>
      <webElementGuid>92ab3c44-6324-483f-abb5-fb0ebafbcedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f895674-b40f-4499-8d23-2624f98000e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>5463984c-e5eb-4538-a80f-52e4ae717a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GLUXZipUpdateInput</value>
      <webElementGuid>198babdf-25ab-47e4-b327-c59e68efad36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>or enter a US zip code</value>
      <webElementGuid>96948bd4-3350-4a6b-a9f3-9e610327fee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>GLUXPostalInputAction</value>
      <webElementGuid>737d4bfa-2ad8-483a-acdc-2e0b1b733836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GLUXZipUpdateInput&quot;)</value>
      <webElementGuid>c060027f-6f03-4e8d-81ea-f182844968ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GLUXZipUpdateInput']</value>
      <webElementGuid>d847f844-905c-48a8-9b9b-456beb4e5eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GLUXZipInputSection']/div/input</value>
      <webElementGuid>fac8a298-cc5a-41bf-b338-406f3b788543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>96c8503e-c1e1-4620-be9b-aa5dac9b8cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'GLUXZipUpdateInput']</value>
      <webElementGuid>dcc11a2d-03b4-46f6-b5d8-7cdbae498583</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
